### ISSUE TITLE
std::rel_ops deprecated in C++20

### ISSUE THREAD

**Issue by hmoffatt** [pubby/flat#10]
Since enabling C++20 support in my project, using Visual Studio 2019 16.11, I am the following warning about std::rel_ops being deprecated.

```
flat_impl.hpp(103,30): warning C4996: 'std::rel_ops': warning STL4027: The namespace std::rel_ops and its contents are deprecated in C++20. Their use is superseded by C++20's <=> operator and automatic rewrites of relational expressions. You can define _SILENCE_CXX20_REL_OPS_DEPRECATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning
```

**Comment by pubby** [comment]
Pushed a quick fix. Lemme know if it fixes the issue.

**Comment by hmoffatt** [comment]
It works. Visual Studio is happy and the container is still working ok (I'm only using vector_map).

On my other systems (Debian linux) I have clang 11 but with libstdc++ 8, which is missing the compare header. I should switch to libc++ until I can upgrade my libstdc++, but until then I changed the check in flat_impl.hpp to

```
#if __cplusplus >= 202002L && __cpp_lib_three_way_comparison >= 201711L
```
