### ISSUE TITLE
Why the restriction on const iterators ? 

### ISSUE THREAD

**Issue by jcelerier** [pubby/flat#2]
Have there really been problems with boost and other flat_map's approaches of having only the key be const ? I understand that in most cases, even if it's slightly inconvenient it can be work-arounded with using the underlying container directly, but consider this code : 
  
          struct timespan { int min, max, offset; }
          flat_map<int, timespan> m_overticks;

          auto node_it = m_overticks.lower_bound(1234);
          if (node_it != m_overticks.end())
          {
            auto& cur = node_it->second;

            if (ot < cur.min)
              cur.min = ot;
            if (ot > cur.max)
            {
              cur.max = ot;
              cur.offset = tick_offset + tick_ms - cur.max;
            }
          }

Here I don't see an easy way except const_cast'ing the value and I'd rather not resort to that...

**Comment by pubby** [comment]
Boost's implementation has non-const keys. That's OK, but not as safe.

You can use the iterator's public `underlying` member to make it non-const. So:

    auto& cur = node_it.underlying->second;

**Comment by pubby** [comment]
BTW the reason its like that is because `vector` can't hold `const` values. It has to hold `std::pair<Key, Mapped>`, which unfortunately can't be casted to `std::pair<const Key, Mapped>&`.

**Comment by jcelerier** [comment]
> Boost's implementation has non-const keys. That's OK, but not as safe

hmm you're right, I mistook it for another map implementation. The only problem is when doing things in range-based for-loops since you don't have access to the iterator :( oh well !
